In [ ]:
from math import sin,  pi
print(sin(0))
print(pi)

from math import *
print(cos(pi/2))




0.0
3.141592653589793
6.123233995736766e-17


Todas las funciones y variables de **math** se insertan directamente en tu espacio de nombres global. Esto puede llevar a conflictos y ambigüedad, ya que diferentes librerias pueden tener funciones con nombres similares.

Si importas todo (*) desde varias bibliotecas, los nombres pueden sobrescribirse entre sí. Por ejemplo, tanto **numpy** como **math** tienen su propia función sin, así que:

si uso sin(), ¿es la de **NumPy** o la de **math**? Es difícil saberlo.

In [ ]:
from numpy import *
from math import *

print(sin(0)) #Is this NumPy’s or math’s sin()? Hard to tell.

0.0


What is the solution?

In [ ]:
import numpy as np #This makes it clear where each function comes from:
import math as math
print(math.cos(math.pi/2))
print(np.sin(math.pi/2))

6.123233995736766e-17
1.0


_____________________________________________________________________________________________

In [2]:
x = [ 1, -2, 2.3, 4]
print(x)
print(type(x))

y = [-1, 2, 3, 4.5]
print(y)

print(x+y)

z = [1, 3, 'x']

print(z+x)
print(x[1])

[1, -2, 2.3, 4]
<class 'list'>
[-1, 2, 3, 4.5]
[1, -2, 2.3, 4, -1, 2, 3, 4.5]
[1, 3, 'x', 1, -2, 2.3, 4]
-2


In [9]:
import numpy as np #This makes it clear where each function comes from:
#from numpy import *
x = np.array([ 1, -2, 2.3, 4])
#y = array([1,0])
print(x)
print(type(x))
print(x[-1])


y = np.array(y)
print(y)
print(x+y)
print(x*y)

a = np.array([1, -2])
print(x)
print(a)
#print (x*a) # it produced a error as it multiples element by element

[ 1.  -2.   2.3  4. ]
<class 'numpy.ndarray'>
4.0
[-1.   2.   3.   4.5]
[0.  0.  5.3 8.5]
[-1.  -4.   6.9 18. ]
[ 1.  -2.   2.3  4. ]


ValueError: operands could not be broadcast together with shapes (2,) (4,) 

# Atributos vs metodos

Los atributos son características o propiedades de un objeto. Representan datos o valores asociados a ese objeto. No se escriben con paréntesis cuando se accede a ellos.

Metodos son funciones asociadas a un objeto.

Describen acciones que el objeto puede realizar.

Se invocan con paréntesis.



In [14]:

x = np.array([ 1, -2, 2.3, 4])
print(len(x))
print(x.shape) # devuelve las dimensiones del arreglo (# filas y/o columnas)


print(x.size) # numero total de elementos

print(x.sum())

TypeError: 'tuple' object is not callable

In [ ]:
z = x.reshape((2,2))
print(z)
print(z.shape)
print(type(z))
print(z[0,1])
print(z[1:]) #it prints all rows from index 1 forward


print(z[:1]) #it prints all row before index 1
print(z[:,1]) # it print the column of index 1

In [ ]:

x = np.array([ 1, -2, 2.3, 4])
print(x)

z = x.reshape((4,1))
print(z)
print(z.shape)
print(type(z))
print(z[1,0])

#it prints all rows and columns starting from row index 0
print(z[0:])
print(z[0:].shape)
print(z[:3])

#it prints all rows, but only column 0
#it gest values as 1-D array
print(z[:,0])
print(z[:,0].shape)

[ 1.  -2.   2.3  4. ]
[[ 1. ]
 [-2. ]
 [ 2.3]
 [ 4. ]]
(4, 1)
<class 'numpy.ndarray'>
-2.0
[[ 1. ]
 [-2. ]
 [ 2.3]
 [ 4. ]]
(4, 1)
[[ 1. ]
 [-2. ]
 [ 2.3]]
[ 1.  -2.   2.3  4. ]
(4,)


In [ ]:
x = np.array([1, 0, -1])
y = np.array ([1, 2, -1])
print("x as 1-D array",x)
print(x.shape)
print(type(x))

print(x+y)
print(x*y)


x = np.matrix([1, 0, -1])
y = np.matrix ([1, 2, -1])
print("x as matrix",x)
print(x.shape)
print(type(x))

print(x+y)
print(x*y.transpose())
print(x.transpose()*y)

x as 1-D array [ 1  0 -1]
(3,)
<class 'numpy.ndarray'>
[ 2  2 -2]
[1 0 1]
x as matrix [[ 1  0 -1]]
(1, 3)
<class 'numpy.matrix'>
[[ 2  2 -2]]
[[2]]
[[ 1  2 -1]
 [ 0  0  0]
 [-1 -2  1]]


In [ ]:

import numpy as np

x = np.array([[1, 0, -1], [-2, -1, 0]])  # 2 rows, 3 columns
y = np.array([1, 2, -1])                # 1D array with shape (3,)

print("x as 2x3 matrix using array:\n", x)
print("x shape:", x.shape)
print("x type:", type(x))

print("x + y:\n", x + y)  # Broadcasting y over rows of x
print("x * y:\n", x * y)  # Element-# wise multiplication with broadcastin


x = np.matrix(x)
y = np.matrix ([1, 2, -1])
print("x as matrix",x)
print(x.shape)
print(type(x))

print(x+y)
print(x*y.transpose())
print(y*x.transpose())

x as 2x3 matrix using array:
 [[ 1  0 -1]
 [-2 -1  0]]
x shape: (2, 3)
x type: <class 'numpy.ndarray'>
x + y:
 [[ 2  2 -2]
 [-1  1 -1]]
x * y:
 [[ 1  0  1]
 [-2 -2  0]]
x as matrix [[ 1  0 -1]
 [-2 -1  0]]
(2, 3)
<class 'numpy.matrix'>
[[ 2  2 -2]
 [-1  1 -1]]
[[ 2]
 [-4]]
[[ 2 -4]]


In [ ]:

import numpy as np

x = np.array([[1, 0, -1], [-2, -1, 0]])  # 2 rows, 3 columns
print("x as array",x)
print(x.shape)
print(type(x))
print(x[0,2])
print(x[0,:])
print(x[:,2])

x = np.matrix(x)
y = np.matrix ([1, 2, -1])
print("x as matrix",x)
print(x.shape)
print(type(x))
print(x[0,2])
print(x[0,:])
print(x[:,2])

x as array [[ 1  0 -1]
 [-2 -1  0]]
(2, 3)
<class 'numpy.ndarray'>
-1
[ 1  0 -1]
[-1  0]
x as matrix [[ 1  0 -1]
 [-2 -1  0]]
(2, 3)
<class 'numpy.matrix'>
-1
[[ 1  0 -1]]
[[-1]
 [ 0]]
